# Generated by Django 4.2.7 on 2023-11-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_formdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormData',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
    ]
