# Generated by Django 4.2.7 on 2023-11-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_formdata_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default=' ', upload_to='home/'),
        ),
    ]
